// FMTO 2.0 — Mister data (sorgente unica)
// Nota: questa mappa è usata sia da mister.html che da squadre/area.
window.MISTERS_DATA = {
  "AJAX": {"nome": "Alessandro", "telegram": "alessandromicciullo", "forum": "ucavadd", "ingresso": "Jun 2020", "ultimo_cambio": ""},
  "ANDERLECHT": {"nome": "Alfredo", "telegram": "Fred994", "forum": "Dieguito94", "ingresso": "May 2021", "ultimo_cambio": ""},
  "ARSENAL": {"nome": "Alessandro", "telegram": "alca_91", "forum": "Alca91", "ingresso": "Sep 2024", "ultimo_cambio": ""},
  "ASTANA": {"nome": "Matteo Marinoni", "telegram": "Mattmari22", "forum": "Mattmari22", "ingresso": "05/03/2026", "ultimo_cambio": ""},
  "ATALANTA": {"nome": "Alex Casinghino", "telegram": "MrAlexDea", "forum": "MrAlex", "ingresso": "Mar 2020", "ultimo_cambio": ""},
  "ATHLETIC BILBAO": {"nome": "Gabriele Righini", "telegram": "Be Positive", "forum": "Be Positive", "ingresso": "Apr 2020", "ultimo_cambio": ""},
  "ATLETICO MADRID": {"nome": "Stefano", "telegram": "SteYoshi", "forum": "SteYoshizu", "ingresso": "May 2025", "ultimo_cambio": ""},
  "AZ ALKMAAR": {"nome": "Loris", "telegram": "cestoris", "forum": "cestoris", "ingresso": "Feb 2023", "ultimo_cambio": "Sep 2024"},
  "BARCELONA": {"nome": "Alessandro", "telegram": "Alexbusa", "forum": "busakoss", "ingresso": "May 2025", "ultimo_cambio": "Dec 2025"},
  "BASILEA": {"nome": "Alberto", "telegram": "SirDerfel", "forum": "SirDerfel", "ingresso": "Nov 2021", "ultimo_cambio": ""},
  "BAYER LEVERKUSEN": {"nome": "", "telegram": "", "forum": "", "ingresso": "", "ultimo_cambio": ""},
  "BAYERN MONACO": {"nome": "Ivan", "telegram": "ivan19928", "forum": "ivan16892", "ingresso": "Mar 2024", "ultimo_cambio": "Jul 2025"},
  "BENFICA": {"nome": "Paolo", "telegram": "paolo", "forum": "Paolo_S77", "ingresso": "Nov 2020", "ultimo_cambio": ""},
  "BODO/GLIMT": {"nome": "Giuseppe Defilippis", "telegram": "gdef12", "forum": "g.def12", "ingresso": "Jan 2026", "ultimo_cambio": ""},
  "BODO-GLIMT": {"nome": "Giuseppe Defilippis", "telegram": "gdef12", "forum": "g.def12", "ingresso": "Jan 2026", "ultimo_cambio": ""},
  "BOLOGNA": {"nome": "Diego", "telegram": "Thefirstlady2025", "forum": "Diemotions87", "ingresso": "Feb 2026", "ultimo_cambio": ""},
  "BORUSSIA DORTMUND": {"nome": "alerosati", "telegram": "alerosati2000", "forum": "alerosati2000", "ingresso": "May 2020", "ultimo_cambio": "Oct 2024"},
  "BORUSSIA MONCHENGLADBACH": {"nome": "Carmeloct46", "telegram": "Carmeloct46", "forum": "Carmeloct46", "ingresso": "Jun 2020", "ultimo_cambio": ""},
  "CELTIC": {"nome": "Luca", "telegram": "ferro197475", "forum": "Ferro50", "ingresso": "Nov 2023", "ultimo_cambio": "Mar 2024"},
  "CHELSEA": {"nome": "Fabrizio", "telegram": "Calonderiel", "forum": "Calonderiel", "ingresso": "Oct 2023", "ultimo_cambio": "Jan 2024"},
  "CLUB BRUGGE": {"nome": "Roberto Sferruzzi", "telegram": "sfero75", "forum": "Sfero75", "ingresso": "Jun 2021", "ultimo_cambio": ""},
  "COPENAGHEN": {"nome": "Giuliano", "telegram": "riccio76", "forum": "giugiu49", "ingresso": "Nov 2024", "ultimo_cambio": "May 2025"},
  "CRYSTAL PALACE": {"nome": "Andrea", "telegram": "Andreav0105", "forum": "Andreav0105", "ingresso": "Nov 2024", "ultimo_cambio": ""},
  "DINAMO KIEV": {"nome": "Luca", "telegram": "L_Lawliet91", "forum": "LucaLawliet", "ingresso": "Jun 2023", "ultimo_cambio": "May 2025"},
  "DINAMO ZAGABRIA": {"nome": "Lorenzo Galluzzo", "telegram": "galluzzolorenzo", "forum": "Lorenzo Galluzzo", "ingresso": "Apr 2020", "ultimo_cambio": ""},
  "EINTRACHT FRANCOFORTE": {"nome": "Federico Luigelli", "telegram": "Federico Luigelli", "forum": "Federico Luigelli", "ingresso": "Jan 2022", "ultimo_cambio": ""},
  "EVERTON": {"nome": "", "telegram": "", "forum": "", "ingresso": "", "ultimo_cambio": ""},
  "FEYENOORD": {"nome": "", "telegram": "", "forum": "", "ingresso": "", "ultimo_cambio": ""},
  "FIORENTINA": {"nome": "Gabriele Cavallaro", "telegram": "gabrieltheyellow", "forum": "gabrieltheyellow", "ingresso": "Feb 2024", "ultimo_cambio": ""},
  "GENT": {"nome": "Alberto Ariatti", "telegram": "albertoariatti", "forum": "Alberto Ariatti", "ingresso": "Dec 2022", "ultimo_cambio": ""},
  "GLASGOW RANGERS": {"nome": "Eurodino", "telegram": "Eurodino", "forum": "Eurodino", "ingresso": "Apr 2021", "ultimo_cambio": ""},
  "INTER": {"nome": "Luca Marcarini", "telegram": "M17GK", "forum": "Mec17", "ingresso": "Mar 2020", "ultimo_cambio": ""},
  "JUVENTUS": {"nome": "Asik85", "telegram": "Parzival1985", "forum": "Asik85", "ingresso": "Mar 2020", "ultimo_cambio": ""},
  "LAZIO": {"nome": "Tony My", "telegram": "tonetto87", "forum": "tonetto87", "ingresso": "Jun 2020", "ultimo_cambio": ""},
  "LEEDS": {"nome": "Vin", "telegram": "vinci994", "forum": "vinci994", "ingresso": "Jan 2025", "ultimo_cambio": "Dec 2025"},
  "LIONE": {"nome": "Alex", "telegram": "welshwizard07", "forum": "Welsh wizard", "ingresso": "Apr 2021", "ultimo_cambio": ""},
  "LIPSIA": {"nome": "Simone", "telegram": "simo319797", "forum": "Simogiunto97", "ingresso": "Dec 2025", "ultimo_cambio": ""},
  "LIVERPOOL": {"nome": "Alberto", "telegram": "whitewolf7432", "forum": "Whitewolf7432", "ingresso": "Sep 2020", "ultimo_cambio": ""},
  "MANCHESTER CITY": {"nome": "Alessandro Frangiosa", "telegram": "lisandro", "forum": "Alefra88", "ingresso": "Mar 2020", "ultimo_cambio": ""},
  "MANCHESTER UNITED": {"nome": "Michele Martinelli", "telegram": "Mikkael90", "forum": "mikkael90", "ingresso": "Feb 2026", "ultimo_cambio": ""},
  "MILAN": {"nome": "Marco Jack Nanni", "telegram": "Marcojacknanni", "forum": "jackdicuori5", "ingresso": "Apr 2021", "ultimo_cambio": ""},
  "MONACO": {"nome": "", "telegram": "", "forum": "", "ingresso": "", "ultimo_cambio": ""},
  "NAPOLI": {"nome": "Vittorio Vaglia", "telegram": "Vjr75", "forum": "Vjr75", "ingresso": "Jun 2024", "ultimo_cambio": "Sep 2025"},
  "NEWCASTLE": {"nome": "Antonio Senserini", "telegram": "Antonio Senserini", "forum": "Antonio Senserini", "ingresso": "Mar 2020", "ultimo_cambio": ""},
  "NOTTINGHAM FOREST": {"nome": "", "telegram": "", "forum": "", "ingresso": "", "ultimo_cambio": ""},
  "OLYMPIAKOS": {"nome": "piesal", "telegram": "piesal09", "forum": "Fabio Pierotti", "ingresso": "Dec 2025", "ultimo_cambio": ""},
  "OLYMPIQUE MARSIGLIA": {"nome": "", "telegram": "", "forum": "", "ingresso": "", "ultimo_cambio": ""},
  "PAOK SALONICCO": {"nome": "Michele Sivilli", "telegram": "Michelone74", "forum": "Michelone 74", "ingresso": "May 2020", "ultimo_cambio": ""},
  "PSG": {"nome": "Tommaso Molin", "telegram": "tommy150788", "forum": "Tommy_8888", "ingresso": "Jun 2020", "ultimo_cambio": "Mar 2023"},
  "PARIS SAINT GERMAIN": {"nome": "Tommaso Molin", "telegram": "tommy150788", "forum": "Tommy_8888", "ingresso": "Jun 2020", "ultimo_cambio": "Mar 2023"},
  "PORTO": {"nome": "Giulio Mercurio", "telegram": "fufo8", "forum": "jmerk1702", "ingresso": "Sep 2025", "ultimo_cambio": ""},
  "PSV": {"nome": "Francesco", "telegram": "AgasiZ", "forum": "Agasiz", "ingresso": "Feb 2026", "ultimo_cambio": ""},
  "REAL BETIS": {"nome": "Luigi Formisano", "telegram": "folu92", "forum": "folu92", "ingresso": "Jul 2020", "ultimo_cambio": ""},
  "BETIS": {"nome": "Luigi Formisano", "telegram": "folu92", "forum": "folu92", "ingresso": "Jul 2020", "ultimo_cambio": ""},
  "REAL MADRID": {"nome": "marco barilla", "telegram": "mandraghe76", "forum": "mandraghe76", "ingresso": "Feb 2021", "ultimo_cambio": ""},
  "REAL SOCIEDAD": {"nome": "Tocci Raffaele", "telegram": "ciaffa69", "forum": "prinz691", "ingresso": "Sep 2020", "ultimo_cambio": ""},
  "ROMA": {"nome": "Manu Nyhr Gdr", "telegram": "NyhrGdr", "forum": "NyhrGaming", "ingresso": "Nov 2020", "ultimo_cambio": "Oct 2023"},
  "SAINT ETIENNE": {"nome": "", "telegram": "", "forum": "", "ingresso": "", "ultimo_cambio": ""},
  "SCHALKE 04": {"nome": "AXEL", "telegram": "RoyFox83", "forum": "AXEL", "ingresso": "Sep 2021", "ultimo_cambio": ""},
  "SIVIGLIA": {"nome": "Lvcaalexis", "telegram": "lvcaalexis", "forum": "lvcaalexis", "ingresso": "Jan 2021", "ultimo_cambio": ""},
  "SPORTING LISBONA": {"nome": "Nando", "telegram": "Hones80", "forum": "Hones80s", "ingresso": "Apr 2021", "ultimo_cambio": ""},
  "STELLA ROSSA": {"nome": "Luigi valentino", "telegram": "Giggio", "forum": "giggio", "ingresso": "Nov 2020", "ultimo_cambio": ""},
  "TOTTENHAM": {"nome": "Osvaldo", "telegram": "Osvaldo13", "forum": "osv98", "ingresso": "Apr 2021", "ultimo_cambio": ""},
  "VALENCIA": {"nome": "Alberto Giglio", "telegram": "albertogiglio", "forum": "giglioa386", "ingresso": "May 2025", "ultimo_cambio": "Dec 2025"},
  "VILLARREAL": {"nome": "Fabio Ceol", "telegram": "fabkey", "forum": "FCL", "ingresso": "Mar 2020", "ultimo_cambio": ""},
  "ZENIT": {"nome": "Antonio Greggio", "telegram": "TonioTaras", "forum": "TonioTaras", "ingresso": "Mar 2023", "ultimo_cambio": "May 2025"}
};

window.getMisterInfo = function getMisterInfo(sqName) {
  var key = String(sqName || '').toUpperCase();
  return (window.MISTERS_DATA && window.MISTERS_DATA[key]) || { nome:'', telegram:'', forum:'', ingresso:'', ultimo_cambio:'' };
};

